### PR TITLE
Deploy: Tests

### PR DESCRIPTION
**Pull request by maximecolin**

### CODE REVIEW

**Comment by nervo** [comment]
Wow, impressive!

**Comment by maximecolin** [comment]
Just, i don't know if i must keep this [file](https://github.com/manala/ansible-roles/blob/5fea0337fb7719d4fbc0ff06676eb42034273a9e/manala.deploy/callback_plugins/manala_deploy_log.pyc) or not.

**Comment by nervo** [comment]
Ah, nice catch @maximecolin.
Simple answer: no, pyc files must be getignored, just like https://github.com/manala/ansible-roles/blob/master/manala.deploy/.gitignore#L2

**Comment by nervo** [comment]
I wonder if we should add rsync package to the testing docker image...
Any opinions ?

**Pull request merged**
