### PR TITLE
[Pam ssh agent auth] Ubuntu, RedHat and CentOS support

### PR DESCRIPTION
**Pull request by juju4**

### CODE REVIEW

**Comment by juju4** [comment]
The two fails on 1/3 wheezy and jessie are lint part:
```
[ANSIBLE0016] Tasks that run when changed should likely be handlers
/srv/role/tasks/ubuntu.yml:12
Task/Handler: meta flush_handlers
```
Suggestion for a better way?

**Comment by juju4** [comment]
Else what is the right way to enable check for xenial and centos7, at least for some roles? Thanks

**Comment by juju4** [comment]
No problem. Just need to know rules.
added you as collaborator

**Comment by hyvs** [comment]
We will not support other OS than debian in near futur. Thanks anyway for your contributing.

**Pull request closed without merging**
